#! /usr/bin/env ruby
require 'rubygems'
require 'fssm'

def rebuild_site(relative)
  puts ">>> Change Detected to: #{relative} <<<"
  output = relative.gsub('.haml', '.html')
  IO.popen("haml #{relative} #{output}") do |io|
    print(io.readpartial(512)) until io.eof?
  end
  puts '>>> Update Complete <<<'
end

puts ">>> Watching for Changes <<<"
FSSM.monitor("#{File.dirname(__FILE__)}", '**/*.haml') do
  update {|base, relative| rebuild_site(relative)}
  delete {|base, relative| rebuild_site(relative)}
  create {|base, relative| rebuild_site(relative)}
end
