require 'rake/clean'

LESS   = FileList['**/*.less']
COFFEE = FileList['**/*.coffee']
JADE   = FileList['mockups/**/*.jade']

CSS  = LESS.ext('css')
JS   = COFFEE.ext('js')
HTML = JADE.ext('html')

CLOBBER.include(CSS, JS, HTML)

rule '.css' => '.less' do |t|
   puts "  LESS #{t.source}"
   sh 'lessc', t.source, t.name
end

rule '.js' => '.coffee' do |t|
   puts "COFFEE #{t.source}"
   sh 'coffee', '-c', t.source
end

rule '.html' => '.jade' do |t|
   puts "JADE   #{t.source}"
   sh 'jade', t.source
end

desc "Build all CSS, JavaScript and static HTML files"
task :default => (CSS + JS + HTML)

desc "Continuously watch for changes and rebuild files"
task :watch => [:default] do
    require 'rubygems'
    require 'fssm'

    def rebuild
        sh 'rake'
        puts "    OK"
        if File.file? 'server.pid'
          Process.kill 'USR2', File.read('server.pid').to_i
        end
    rescue
        nil
    end

    begin
        FSSM.monitor(nil, ['**/*.coffee', '**/*.less', '**/*.jade']) do
            update { rebuild }
            delete { rebuild }
            create { rebuild }
        end
    rescue FSSM::CallbackError => e
        Process.exit
    end
end

desc "Run the development server of the application"
task :run do
    # sh 'supervisor -w app.js -p app.js'
    sh 'screen -Rx -p='
end
