#!/usr/bin/env python
import os, sys
from PIL import Image
from hashlib import sha1

HEADER = '''(function(){(window.MakeApp = window.MakeApp || {}).imageDirectories = {
'''

DIR_HEADER = ''' '%s': [
'''

IMAGE = '''  {f: '%s', h: '%s', s: '%dx%d'},
'''

DIR_FOOTER = ''' ],
'''

FOOTER = '''};})();
'''


sys.stdout.write(HEADER)
for i in sys.argv[1:]:
    sys.stdout.write(DIR_HEADER % i)
    for f in os.listdir(i):
        img = Image.open(os.path.join(i, f))
        w, h = img.size
        del img
        fh = open(os.path.join(i, f))
        hsh = sha1(fh.read()).hexdigest()
        del fh
        sys.stdout.write(IMAGE % (f, hsh, w, h))
    sys.stdout.write(DIR_FOOTER)
sys.stdout.write(FOOTER)


#sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'web'))
#import png
#file_name = sys.argv[1]
#sw, sh, spix, smeta = png.Reader(file=open(file_name, 'rb')).asRGBA8()
#print '%dx%d' % (sw, sh)
