#! /bin/bash
cd $(dirname $0)/..
DIR=$(pwd)
screen -X screen scripts/start-mongo
screen -X screen scripts/start-watch
screen -X screen scripts/start-livereload
screen -X screen scripts/start-node
screen -X screen scripts/start-redis
