application: mockkodesigner
version: v0-9-1
runtime: python
api_version: 1

handlers:

# Boring stuff

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Production

- url: /designer
  static_files: minified/designer.min.html
  upload: minified/designer.min.html
  expiration: "0s"
  login: required

- url: /static/designer\.min\.js
  static_files: minified/designer.min.js
  upload: minified/designer.min.js
  expiration: "3650d"
  
- url: /static/theme/theme\.min\.css
  static_files: minified/theme.min.css
  upload: minified/theme.min.css
  expiration: "3650d"
  
- url: /static/iphone/iphone\.min\.css
  static_files: minified/iphone.min.css
  upload: minified/iphone.min.css
  expiration: "3650d"

- url: /static/iphone/images/(.*)
  static_files: static/iphone/images/\1
  upload: static/iphone/images/.*
  expiration: "3650d"

- url: /static/theme/images/(.*)
  static_files: static/theme/images/\1
  upload: static/theme/images/.*
  expiration: "3650d"

- url: /static/home/
  static_dir: static/home/

- url: /static/home\.(js|css)
  static_files: static/home.\1
  upload: static/home\.(js|css)

# "Run app" support. This is only needed to be public until #3920145 is fixed
# ("Run app" should use the same css as designer)

- url: /static/iphone/iphone.css
  static_files: static/iphone/iphone.css
  upload: static/iphone/iphone.css
  # login: admin
- url: /static/iphone/images
  static_dir: static/iphone/images
  # login: admin
- url: /static/lib
  static_dir: static/lib

## Development

- url: /
  static_files: home.html
  upload: home.html

- url: /dev
  static_files: designer.html
  upload: designer.html
  login: admin

- url: /static/designer((?:-.*)?)\.js
  static_files: static/designer\1.js
  upload: static/designer(-.*)?\.js
  login: admin

- url: /static/jpicker.js
  static_files: static/jpicker.js
  upload: static/jpicker.js
  login: admin

- url: /static/theme/theme(-.*).css
  static_files: static/theme/theme\1.css
  upload: static/theme/theme-.*.css
  login: admin

- url: /static/theme/images
  static_dir: static/theme/images
  login: admin

# Webios

- url: /webios/
  static_files: webios/demo.html
  upload: webios/demo.html

- url: /webios/(.*\.(?:html|js|css|coffee|less|haml|png))
  static_files: webios/\1
  upload: webios/.*\.(?:html|js|css|coffee|less|haml|png)

# Other boring stuff

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /admin/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  # login: admin <- handled by appstats itself

# Catch-all

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: App Stats
    url: /admin/stats

derived_file_type:
- python_precompiled

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.less
- ^(.*/)?.*\.haml
